insert into companies (name, mega_url, status, notes)
select v.name, v.mega_url, v.status, v.notes
from (values
  ('АБЛАМИЛК ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/zqBkFLgR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АБЛАМИЛК ЕООД   - № 25'),
  ('АЙ ТРЕЙДИНГ ЛАБ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3uw1QArL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АЙ ТРЕЙДИНГ ЛАБ ЕООД № 210'),
  ('АКВА-ТЕХ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/zvYC0TyY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АКВА-ТЕХ ООД   - № 19'),
  ('АЛБЕРО ВЕРДЕ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/fnBylTDb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АЛБЕРО ВЕРДЕ ЕООД - № 237'),
  ('АЛИСАЛ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/frYG1TzT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АЛИСАЛ ЕООД № 118'),
  ('АЛФА КОММЕРС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/K6J2EBrA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АЛФА КОММЕРС ЕООД'),
  ('Алфа Фарм ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/ryIXhLKC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Алфа Фарм ЕООД № 193'),
  ('АЛХИМ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/63IUjBJZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АЛХИМ ЕООД - № 20'),
  ('АРДАСТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/f34VBDII', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АРДАСТРОЙ ЕООД № 226'),
  ('АРЕКС ФУУД ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/vqBHGTpJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АРЕКС ФУУД ЕООД № 73'),
  ('АРОКС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Xv5EjYhL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АРОКС ЕООД № 150'),
  ('АСС - СИНКО ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/6vg1ETrb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АСС - СИНКО ЕООД № 108'),
  ('АСТ ПОПКОРН ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/qzxWhRLB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АСТ ПОПКОРН ООД № 138'),
  ('АТЛАНТА ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/uqoARIrD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АТЛАНТА ЕООД № 109'),
  ('АТОМЕНЕРГОРЕМОНТ АД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/jiwEwKCT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / АТОМЕНЕРГОРЕМОНТ АД'),
  ('БАЛАДА - ГРУП ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/PzpQyZZI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БАЛАДА - ГРУП ЕООД № 146'),
  ('БАЛКАНРЕМОНТ ИНЖЕНЕРИНГ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/yiQ2TBLJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БАЛКАНРЕМОНТ ИНЖЕНЕРИНГ ООД  - № 18'),
  ('БАТ СОТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/PuIHRLqY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БАТ СОТ ЕООД - № 168'),
  ('БЕЛАТ КОНСТРАКШЪН ГРУП ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/W3hzlRqL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БЕЛАТ КОНСТРАКШЪН ГРУП ООД № 230'),
  ('Бестия Пет ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/emwSjKpR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Бестия Пет ЕООД № 231'),
  ('БИ ЕС ПРОЕКТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/v6gwRTja', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БИ ЕС ПРОЕКТ ЕООД № 128'),
  ('БиЕкспертс ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/fugklbxZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БиЕкспертс ООД № 221'),
  ('БИЗНЕС ФАСИЛИТИ СЪРВИСИЗ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/D7ZmXJIY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БИЗНЕС ФАСИЛИТИ СЪРВИСИЗ ЕООД -  № 22'),
  ('БИЛДИНГ ГРУП - 2000 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/36xQ3SQS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БИЛДИНГ ГРУП - 2000 ЕООД  № 131'),
  ('БИОПЛАСТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/bnQ0VZjC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БИОПЛАСТ  ЕООД  - № 16'),
  ('БЛАГОВЕСТ 89 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/zzQXwZxS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БЛАГОВЕСТ 89 ЕООД № 90'),
  ('Блускай Аутомотив България ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/GihB1ZQJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Блускай Аутомотив България ЕООД № 121'),
  ('БМТ-КОНСУЛТ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/rqoFSQRb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БМТ-КОНСУЛТ ООД № 179'),
  ('БОБО ИНЖЕНЕРИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/q6ZmRb7B', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БОБО ИНЖЕНЕРИНГ ЕООД № 77'),
  ('БОБСТРОЙ БГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HjIGxTCR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БОБСТРОЙ БГ ЕООД № 68'),
  ('БОГОМИЛСТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/ym4hHDqB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БОГОМИЛСТРОЙ ЕООД - № 32'),
  ('БОНЕЛ ТРЕЙД ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/PjwAQTwC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БОНЕЛ ТРЕЙД ЕООД № 155'),
  ('БОР ЛЕС 2017 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/SvwxQJCI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БОР ЛЕС 2017 ЕООД № 180'),
  ('Браманд ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3zZmlRaY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Браманд ЕООД  № 33'),
  ('БРАТЯ ПАЛОВИ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/66p1kZrT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БРАТЯ ПАЛОВИ ЕООД № 120'),
  ('БРАТЯ ПАНЧЕВИ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/DjBGnZ6L', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БРАТЯ ПАНЧЕВИ ООД № 134'),
  ('БСА-Оферта за одит-бланка TSV', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БСА-Оферта за одит-бланка_TSV'),
  ('Бул смарт канстръкшън ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/qr4lnYQJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Бул смарт канстръкшън ЕООД № 211'),
  ('Булбилд Гранд инженеринг ЕООД № - 195', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/inwTiRwI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Булбилд Гранд инженеринг ЕООД № - 195'),
  ('БУЛТЕКС 99 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/7rRXzLiZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БУЛТЕКС 99 ЕООД'),
  ('БУЛТЕКСТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/byJ12RqZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БУЛТЕКСТРОЙ ЕООД -  № 3'),
  ('БЪЛГАРСКА ФИНАНСОВА ГРУПА ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/TzAwgTTY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / БЪЛГАРСКА ФИНАНСОВА ГРУПА ООД  № 26'),
  ('ВАГО ВУУД КОМЕРС ЕООД ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/quA0SJaD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВАГО ВУУД КОМЕРС ЕООД  ЕООД - № 10'),
  ('ВАДИМ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/r2oSVKwK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВАДИМ ООД № 64'),
  ('ВАЛМИЛК ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/PmIADbBT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВАЛМИЛК ЕООД № 65'),
  ('ВЕНИТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3zYmgTpL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВЕНИТ  ЕООД № 75'),
  ('ВИВАВЕЛ БЪЛГАРИЯ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/DipwWQwA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВИВАВЕЛ БЪЛГАРИЯ ЕООД № 136'),
  ('ВИД СТРОЙ - 59 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/v75kwara', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВИД СТРОЙ - 59 ЕООД'),
  ('ВИКТТИ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/frQ2VLrQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВИКТТИ ЕООД № 151'),
  ('ВИЛ ЛЕС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/u7hByb6I', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВИЛ ЛЕС ЕООД № 156'),
  ('ВИТОША ГАЗ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/D2IkQRRJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВИТОША ГАЗ ЕООД  № 34'),
  ('Витоша Клауд Консултинг ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/a7gmBYJA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Витоша Клауд Консултинг ООД'),
  ('ВНВ ТРАНС 1 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/fz4AXLBZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВНВ ТРАНС 1 ООД'),
  ('ВТА Секюрити Сървиз ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/X6YSQLLL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ВТА Секюрити Сървиз ЕООД № 61'),
  ('Г.Гетов ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/O6AGmTiT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Г.Гетов ЕООД № 83'),
  ('Г.М. ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/TmgjkBAT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Г.М. ООД № 140'),
  ('ГАП-07 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/2uJlWCCJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ГАП-07 ЕООД № 98'),
  ('ГАРАНТСТРОЙ-ТРАЙКОВ 96 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/u64niSpI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ГАРАНТСТРОЙ-ТРАЙКОВ 96 ЕООД  № 119'),
  ('ГЕОДИМ ПРОПЪРТИС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/f7g2BZqI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ГЕОДИМ ПРОПЪРТИС ЕООД № 172'),
  ('ГОШКО ПОКРИВИ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/vnQwRbzA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ГОШКО ПОКРИВИ ЕООД - № 76'),
  ('ГРАНД ФАСИЛИТИ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/LyhgiKyL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ГРАНД ФАСИЛИТИ ЕООД - № 194'),
  ('Грижа и чистота ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Wrw3lKDJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Грижа и чистота ООД - № 17'),
  ('Грийн Хаус БГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/XmIDVbhY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Грийн Хаус БГ ЕООД - № 78'),
  ('ГРИЙНБЪРН ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/WvBmDbJS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ГРИЙНБЪРН ЕООД - № 196'),
  ('ДАБЪЛ Д ГРУП ФУУД ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/a2RjiJpC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДАБЪЛ Д ГРУП ФУУД ЕООД - № 197'),
  ('ДАРИ СТРОЙ ГРУП ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OuAWWbAB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДАРИ СТРОЙ ГРУП ЕООД - № 129'),
  ('ДЕОН-БГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/LjYnAB4a', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДЕОН-БГ ЕООД № 212'),
  ('ДЖЕНЕРАЛ КОНСТРУКШЪН ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HqRg0RwA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДЖЕНЕРАЛ КОНСТРУКШЪН ЕООД № 225'),
  ('Джи и Ей ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HiQWybbL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Джи и Ей ЕООД № 97'),
  ('ДЖИ КОНСУЛТ 91 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/fywmwTBL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДЖИ КОНСУЛТ 91 ЕООД - № 45'),
  ('ДИ АР АР КОНСТРЪКШЪНС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/r7ZmyZiQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДИ АР АР КОНСТРЪКШЪНС ЕООД  № 52'),
  ('ДИ ДЖИ ПИ ИНЖЕНЕРИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/v6xCGaSL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДИ ДЖИ ПИ ИНЖЕНЕРИНГ ЕООД'),
  ('Ди Ти Ай Солюшънс ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Pug3VQhI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Ди Ти Ай Солюшънс ООД № 213'),
  ('ДИАНА 7 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/235hAarT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДИАНА 7 ООД № 214'),
  ('Дигиталстрой ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/22o3kQga', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Дигиталстрой ЕООД № 232'),
  ('Добруджа кабел ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/yjg0TQDa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Добруджа кабел ЕООД № 54'),
  ('ДП БИЛД ИНВЕСТМЪНТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/GqZUSBYK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДП БИЛД ИНВЕСТМЪНТ ЕООД № 88'),
  ('ДРААТ ХАНДЕЛ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/WzhBzJ4K', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ДРААТ ХАНДЕЛ ЕООД № 144'),
  ('Дрийм Криейтърс ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/fygzEQYT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Дрийм Криейтърс ЕООД № 111'),
  ('ЕВРО ТИМБЪР ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/y2ZAyJ7B', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕВРО ТИМБЪР ЕООД № 72'),
  ('ЕВРОБУЛПРОДЖЕКТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/myJmUJJL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕВРОБУЛПРОДЖЕКТ ЕООД № 81'),
  ('ЕВРОФОНД КЪНСЪЛТИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/6zAREB4S', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕВРОФОНД КЪНСЪЛТИНГ ЕООД № 80'),
  ('ЕДЕЛВАЙС 1970 ООД № - 198', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/nioDFabT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕДЕЛВАЙС 1970 ООД № - 198'),
  ('ЕКО ГЛОБЪЛ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/zvJGVRJK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕКО ГЛОБЪЛ ООД № 86'),
  ('ЕКСПЕРТ ДИСИЖЪНС ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/SvJk3TAK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕКСПЕРТ ДИСИЖЪНС ООД № 145'),
  ('ЕЛЕГАНТ СИСТЕМС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/CmJXUBDT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕЛЕГАНТ СИСТЕМС ЕООД'),
  ('ЕМ СТРОЙ - 56 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/2v4gALIS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕМ СТРОЙ - 56 ЕООД № 224'),
  ('ЕМЕК БЪЛГАРИЯ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/K2QH3TgZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕМЕК БЪЛГАРИЯ ЕООД'),
  ('ЕН ДЖИ БЕЙКЪРИ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/j6JW2R7T', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕН ДЖИ БЕЙКЪРИ  ЕООД - № 15'),
  ('Ен Ти конструкт ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/CvpWCbwR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Ен Ти конструкт ЕООД - № 39'),
  ('ЕНДУРОСАТ ГАВЪРНМЪНТ ЕНД ДИФЕНС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/iz4yGbRa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕНДУРОСАТ ГАВЪРНМЪНТ ЕНД ДИФЕНС ЕООД'),
  ('ЕНДУРОСАТ ЕАД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/qjY1SRCa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕНДУРОСАТ ЕАД № 216'),
  ('ЕНЕРГИЯ ТЪРГОВИЩЕ АД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3n5GBJJZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕНЕРГИЯ ТЪРГОВИЩЕ АД № 157'),
  ('ЕНЕРДЖИ ТРЕЙД 2009 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HjQggBrB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕНЕРДЖИ ТРЕЙД 2009 ООД -  № 199'),
  ('Ер билдинг Груп ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/T3QxkRgQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Ер билдинг Груп ЕООД № 159'),
  ('Естет-Мебел ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/z7pUGbDA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Естет-Мебел ЕООД № 217'),
  ('ЕТ ДАРИНКА ГАНЕВА', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3vxQBBaJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕТ ДАРИНКА ГАНЕВА - № 200'),
  ('ЕТ ФАИК ЕЛЕБАШЪ - 91', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/m6xFlBDJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕТ ФАИК ЕЛЕБАШЪ - 91  № 41'),
  ('ЕТ ХРИСТО ЦОНКОВСКИ', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/PvxByYoS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕТ ХРИСТО ЦОНКОВСКИ - № 201'),
  ('ЕТРА - ЕЛ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/KjpCHCBQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЕТРА - ЕЛ ООД № 220'),
  ('ЗДРАВЕЦ 7410 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/6vZXwbqS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЗДРАВЕЦ 7410 ЕООД - № 202'),
  ('И Ар Пи България ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/33IigZxS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / И Ар Пи България ЕООД № 30'),
  ('ИВЕНТИ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/S2AWSBKZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИВЕНТИ ООД № 31'),
  ('ИВТ ДИВЕЛЪПМЪНТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/ymRH0bQL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИВТ ДИВЕЛЪПМЪНТ ЕООД № 218'),
  ('ИВТ КОНСУЛТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/6roRkTwD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИВТ КОНСУЛТ ЕООД  № 53'),
  ('ИГА - СТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/rnQ3QDIL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИГА - СТРОЙ ЕООД № 186'),
  ('ИлийчоСтрой ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/evpEXIhT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИлийчоСтрой ЕООД № 152'),
  ('ИНВЕСТ ИН 97 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/q6YA3TAY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИНВЕСТ ИН 97 ЕООД № 44'),
  ('ИНВЕСТ ИН 99 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/j6xUwaKS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИНВЕСТ ИН 99 ЕООД № 188'),
  ('ИНВЕСТМЪНТ ПРОДЖЕКТ МЕНИДЖМЪНТ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/i7ZylJLD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИНВЕСТМЪНТ ПРОДЖЕКТ МЕНИДЖМЪНТ ООД № 60'),
  ('Индустриални батерии ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/n6J1WTKb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Индустриални батерии ЕООД № 57'),
  ('Индустриални суровини ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/33pylBYS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Индустриални суровини ЕООД № 219'),
  ('ИноваСтил ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/y7wUzTxJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИноваСтил ЕООД № 116'),
  ('Иновикс МК ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3zwWHKDC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Иновикс МК ЕООД № 235'),
  ('Интермедика Груп ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Pmh2jI7A', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Интермедика Груп ЕООД № 130'),
  ('Инфрастрой 76 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/q25wQKJD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Инфрастрой 76 ЕООД № 110'),
  ('ИПО ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/72ZgXDqC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ИПО ООД № 91'),
  ('КА - ИМПЕКС ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/L3R2xR6L', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КА - ИМПЕКС ООД - № 11'),
  ('календар одитори 2025', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / календар одитори 2025'),
  ('Каприкорн Кемикълс Груп ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/q2JwAB7B', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Каприкорн Кемикълс Груп ООД   - № 21'),
  ('Капс Ловеч ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/f2QU2Rxa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Капс Ловеч ООД № 92'),
  ('КАРГО ЛАЙН ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/S2xWBYCQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КАРГО ЛАЙН ЕООД № 141'),
  ('КАСКОТРЕЙД ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/y3hEWLhS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КАСКОТРЕЙД ЕООД № 227'),
  ('КМП БИЛД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3vR33Qaa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КМП БИЛД № 51'),
  ('КОЗИРОГ-95 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OvgnTaZA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КОЗИРОГ-95 ЕООД № 149'),
  ('Колд пойнт ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Pj5BQLJY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Колд пойнт ООД № 223'),
  ('КОМФОРТЪБЪЛ ЕООД № - 203', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/KnQ2Gb6I', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КОМФОРТЪБЪЛ ЕООД № - 203'),
  ('КОНСОРЦИУМ СМАРТ ЕКО ПАКС СОЛУШЪНС ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Gq5AGBqQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КОНСОРЦИУМ СМАРТ ЕКО ПАКС СОЛУШЪНС ООД № 122'),
  ('Контрон БГ Проект ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OzwBAaBL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Контрон БГ Проект ЕООД № 142'),
  ('КОНТРОН БЪЛГАРИЯ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/K3QSzb7J', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КОНТРОН БЪЛГАРИЯ ООД № 89'),
  ('КОТЕК ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/L3ohHbLa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КОТЕК ЕООД № 67'),
  ('КРАСИЛЕС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HuoSlICL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КРАСИЛЕС  ЕООД №  4'),
  ('КРЕВ 21 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HqxkTKjK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КРЕВ 21 ООД № 114'),
  ('Кристал Сити ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/emYBjZDZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Кристал Сити ЕООД № 191'),
  ('КУБАР СТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/76QATBrZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / КУБАР СТРОЙ ЕООД - № 187'),
  ('ЛИДЕР КОНСТРУКТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/LrJ0XLqB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЛИДЕР КОНСТРУКТ ЕООД  - № 8'),
  ('ЛИДЕРПРОЕКТ ЕООД - 204', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3yQTmDaT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЛИДЕРПРОЕКТ ЕООД  - 204'),
  ('ЛИМК БГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/ejYGHLRT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЛИМК БГ ЕООД'),
  ('Лоби Кар Транс и Ко ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/a7J3EbwJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Лоби Кар Транс и Ко ЕООД'),
  ('ЛЮВАНТРАНС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/qqAThJbK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЛЮВАНТРАНС ЕООД № 154'),
  ('М-ХАУС2011 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Cj4iySqD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / М-ХАУС2011 ЕООД № 205'),
  ('МАИВ БИЛД ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/anIixT7B', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МАИВ БИЛД ООД № 40'),
  ('Макс Еко Транс ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/yrwXHIJb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Макс Еко Транс ЕООД'),
  ('Максмарт ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/nmwnTLbA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Максмарт ЕООД № 169'),
  ('МАРИЦА ОЛИО АД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Wm5WRBYT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МАРИЦА ОЛИО АД № 170'),
  ('МАРС АРМОР ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/yuRjnBzY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МАРС АРМОР ООД № 173'),
  ('МЕАЦА ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Sy4yQKxL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МЕАЦА ЕООД'),
  ('Мегастрой-МК ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/qz5VlB7L', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Мегастрой-МК ЕООД'),
  ('МЕДЕВ-79 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/q7wkESbK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МЕДЕВ-79 ЕООД № 123'),
  ('Меди Кеър', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/mmZgGJ7A', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Меди Кеър № 70'),
  ('МЗМ - СТРОЙ 99 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/y7gzXBwY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МЗМ - СТРОЙ 99 ЕООД № 182'),
  ('Мил-Мар 80 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/LqQzlbSA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Мил-Мар 80 ЕООД'),
  ('МИЛАДОМ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OqBExBAD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МИЛАДОМ ООД № 46'),
  ('Миноар', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/z6gUxZCa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Миноар'),
  ('Мир Инженеринг ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/72A3TTaa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Мир Инженеринг ЕООД'),
  ('МКХ Билдинг ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/D74w2J5Y', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МКХ Билдинг ЕООД  № 13'),
  ('МЛ Инженеринг ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/qjoxGDZD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МЛ Инженеринг ЕООД №  117'),
  ('МОЛЕКЮЛАР СОЛУШЪНС БЪЛГАРИЯ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/vjBgzDbS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МОЛЕКЮЛАР СОЛУШЪНС БЪЛГАРИЯ ЕООД № 153'),
  ('МОНТАЖСТРОЙ ИНЖЕНЕРИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/36oAQZKD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МОНТАЖСТРОЙ ИНЖЕНЕРИНГ ЕООД № 164'),
  ('МУЛТИПЛЕКС ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/6yZ13SwB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МУЛТИПЛЕКС ООД № 112'),
  ('МУРА-ЛЕС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/b6BUQZjC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / МУРА-ЛЕС ЕООД № 124'),
  ('Н и Н КОМПЛЕКС СТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/32pwzAyD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Н и Н КОМПЛЕКС СТРОЙ ЕООД № 113'),
  ('НАД ДИЗАИН ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/KuJGHJTA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / НАД ДИЗАИН ЕООД № 36'),
  ('НАС БГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/inpQiTqb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / НАС БГ ЕООД № 100'),
  ('Нестос Фешън', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/6jRkURRR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Нестос Фешън № 47'),
  ('НИГ СТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/2yRR0LqZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / НИГ СТРОЙ ЕООД № 167'),
  ('НИЕ МОЖЕМ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OiwEVYjL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / НИЕ МОЖЕМ ЕООД'),
  ('НИКОНИ БИЛД БГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/S7RVzLTB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / НИКОНИ БИЛД БГ ЕООД № 181'),
  ('Нов - А строй ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Ljh2gQrA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Нов - А строй ЕООД'),
  ('Нова Траннслйет ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/byAEFZzC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Нова Траннслйет  ЕООД № 48'),
  ('НОЕЛ ИНЖЕНЕРИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/K752QARb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / НОЕЛ ИНЖЕНЕРИНГ ЕООД № 166'),
  ('НЮ ДАЙРЕКШЪНС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/DywBmLZA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / НЮ ДАЙРЕКШЪНС ЕООД № 192'),
  ('НЮ СОЛАР ПРОДЖЕКТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/muwSHIKT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / НЮ СОЛАР ПРОДЖЕКТ ЕООД'),
  ('ОГРАДНИ СИСТЕМИ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/nuJAwTQZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ОГРАДНИ СИСТЕМИ ЕООД № 87'),
  ('ОЙЛ ФУУД ТЕХНОЛЪДЖИС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/L3gDXSpB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ОЙЛ ФУУД ТЕХНОЛЪДЖИС ЕООД № 125'),
  ('ОРАК ИНЖЕНЕРИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/SvZmhBhb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ОРАК ИНЖЕНЕРИНГ  ЕООД  № 27'),
  ('ОФИС ТРЕНД ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/aqoCgKZI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ОФИС ТРЕНД ООД № 228'),
  ('Пелетни камини и котли ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/DuIljZLY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Пелетни камини и котли ЕООД № 59'),
  ('ПЕРЛАМЕТ СЕ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/2zoxmChA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПЕРЛАМЕТ СЕ ООД № 101'),
  ('ПЕТРОНИКС ГРУП ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/XjhQ2CbD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПЕТРОНИКС ГРУП ЕООД № 171'),
  ('ПЕХА ТЕХ ЕНД ТРЕЙД ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/DuAnUbJT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПЕХА ТЕХ ЕНД ТРЕЙД ЕООД № 183'),
  ('Пи Ен Джи Груп ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/r7YRgLZL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Пи Ен Джи Груп ЕООД № 189'),
  ('ПИСАРСКИ ДИЗАЙН ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/TnQBABKT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПИСАРСКИ ДИЗАЙН ЕООД  № 102'),
  ('ПКЛИЙН ГРУП ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/GuAE0DBR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПКЛИЙН ГРУП ЕООД № 236'),
  ('ПЛ ПРОДЖЕКТ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/a6IyxDIY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПЛ ПРОДЖЕКТ ООД № 62'),
  ('ПЛАНТА ФРУКТ ЕКСПОРТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/jzJDUCKY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПЛАНТА ФРУКТ ЕКСПОРТ ЕООД'),
  ('ПЛОД - ФАМ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/yjwDEZhB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПЛОД - ФАМ ЕООД № 56'),
  ('ПМГ БИЛД ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/iyBAQZDL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПМГ БИЛД ЕООД № 96'),
  ('Поасон Дор ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/XmB0SJ4a', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Поасон Дор ЕООД № 38'),
  ('ПОЛИХИМ - СС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HmBmiByL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПОЛИХИМ - СС ЕООД № 206'),
  ('ПРЕМИУМ ИНЖЕНЕРИНГ ГРУП ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/qnB0nJDI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПРЕМИУМ ИНЖЕНЕРИНГ ГРУП ЕООД № 147'),
  ('ПРИНТ ЮНАЙТЕД ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/W7h0FaZB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПРИНТ ЮНАЙТЕД ООД'),
  ('Принтек България ЕАД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/C7RTVRLA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Принтек България ЕАД № 174'),
  ('Про Секюрити Груп ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/z3hFlDQY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Про Секюрити Груп ООД № 233'),
  ('ПРОАРХ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/TuJ0EJbD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПРОАРХ  ЕООД - № 1'),
  ('Пролет ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/KnRAlZpL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Пролет  ЕООД № 55'),
  ('ПроМедЕксперт АД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/CyoF1ZwL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПроМедЕксперт АД № 207'),
  ('ПРОФЕСИОНАЛ - 777 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/TuZk2DjA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПРОФЕСИОНАЛ - 777  ООД -  № 14'),
  ('ПРОФЕСИОНАЛНА ЗАЩИТА – ЕЛЕКТРОНИК ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HuBS1RSZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ПРОФЕСИОНАЛНА ЗАЩИТА – ЕЛЕКТРОНИК  ООД  - № 23'),
  ('Равнако ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/erQm3TwK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Равнако ООД № 93'),
  ('РАЯ-96 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/WzZiSZBB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / РАЯ-96 ООД № 63'),
  ('РВ КЪМПАНИ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/j6AR0DLY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / РВ КЪМПАНИ ЕООД № 103'),
  ('Рилана ЕАД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Gn5xVBRL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Рилана ЕАД'),
  ('РОНА ИНВЕСТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OvAhCJxb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / РОНА ИНВЕСТ ЕООД № 184'),
  ('РУЛИП ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/vjIjwJoZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / РУЛИП ЕООД № 105'),
  ('РУСЕВПЛАСТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/ujZi1DgS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / РУСЕВПЛАСТ ЕООД № 84'),
  ('С Тръст Груп ЕООД № - 9', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/PmYmFBoY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / С Тръст Груп ЕООД  № - 9'),
  ('С ТРЪСТ ЕНТЕРПРАИЗ АД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/erg2iZSJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / С ТРЪСТ ЕНТЕРПРАИЗ АД № 135'),
  ('САГА-К ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/m2RmnTzC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / САГА-К ЕООД № 175'),
  ('САЙТЪР ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/yqQgyZrL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / САЙТЪР ЕООД № 104'),
  ('САЛОНИТА ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/6z4ggLRb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / САЛОНИТА ООД № 185'),
  ('САТИКА ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/a3ph3DpQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / САТИКА ЕООД № 137'),
  ('СВЕТМЕД ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/fuhEiA6A', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СВЕТМЕД ЕООД № 162'),
  ('СД АКВА СТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/G651wQjB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СД АКВА СТРОЙ ЕООД № 163'),
  ('СЕРВИЗЕН ЦЕНТЪР ЗА МЕТАЛИ ЕАД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/32wg3aBa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СЕРВИЗЕН ЦЕНТЪР ЗА МЕТАЛИ ЕАД № 158'),
  ('СЕРТИФИКАЦИЯ', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ'),
  ('СИКО СОЛАР ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/aypGWTbA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СИКО СОЛАР ЕООД № 148'),
  ('СИТИ СТРОЙ 2025 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/jvhyHYrS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СИТИ СТРОЙ 2025 ЕООД'),
  ('Ситиком Рила ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/7ihACIxD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Ситиком Рила ООД № 24'),
  ('СКАЙ МЕДИКЪЛ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OjQjlbTb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СКАЙ МЕДИКЪЛ ООД № 178'),
  ('СКАЙ ПРАЙМ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/amwRRLwI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СКАЙ ПРАЙМ ЕООД'),
  ('СКАПТО ТРЕЙД ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/y2QFETaZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СКАПТО ТРЕЙД ООД № 95'),
  ('СЛЪНЧЕВА ТРАКИЯ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/GiJnVYKJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СЛЪНЧЕВА ТРАКИЯ ООД № 49'),
  ('СМП ПЛЕВЕН ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/H2o0DaTL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СМП ПЛЕВЕН ЕООД № 139'),
  ('СОРИКО ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/umQiATJT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СОРИКО ООД № 85'),
  ('СПЕЦИАЛНИ ПОЛИМЕРИ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3nwnSKLL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СПЕЦИАЛНИ ПОЛИМЕРИ ООД № 115'),
  ('СПИЙД СЕКЮРИТИ 78 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/PvwT2QTQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СПИЙД СЕКЮРИТИ 78 ЕООД'),
  ('СПИРОВ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Dyx3kaKL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СПИРОВ ООД'),
  ('СТОПЕР 90 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HnQVlL6K', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СТОПЕР 90 ЕООД № 161'),
  ('СТРОЙГРУП ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/7uh0UawA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СТРОЙГРУП ЕООД'),
  ('СУПЕРНОВА ИНЖЕНЕРИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3qhDAATA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СУПЕРНОВА ИНЖЕНЕРИНГ ЕООД - № 106'),
  ('Сънигранд ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/DiZDiL4J', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Сънигранд ЕООД № 79'),
  ('СЪНТЕРА ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/aix21CTR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / СЪНТЕРА ЕООД № 229'),
  ('ТЕМПЕКС', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/mzIwBBCS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТЕМПЕКС № 74'),
  ('ТЕРМО - ЛУКС I ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/v3QASZ7Y', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТЕРМО - ЛУКС I ООД'),
  ('ТЕХКОНСТРУКТ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/GvpD1ZhR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТЕХКОНСТРУКТ ЕООД № 82'),
  ('ТЕХНОМЕДИКЪЛ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/36JC1ZDK', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТЕХНОМЕДИКЪЛ ЕООД № 208'),
  ('ТЕХНОПРОЕКТПЛАСТ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/KyQ2DDBS', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТЕХНОПРОЕКТПЛАСТ ООД  -№ 6'),
  ('ТЕХНОСТРОЙ – ИНЖЕНЕРИНГ 99 АД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/evIAxThD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТЕХНОСТРОЙ – ИНЖЕНЕРИНГ 99 АД  № 29'),
  ('ТИФЛЕКС 1 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/HmQCybjL', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТИФЛЕКС 1 ЕООД  -  №  7'),
  ('ТОДИС ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/WyRkRBZB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТОДИС ЕООД № 71'),
  ('ТОНИ ГРУП 76 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OzhUyZYC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТОНИ ГРУП 76 ЕООД № 28'),
  ('ТОПЛИВО-ЮГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Wv5UDITT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТОПЛИВО-ЮГ ЕООД  № 43'),
  ('ТРАЙКО СТРОЙ БГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/3u4khJgR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТРАЙКО СТРОЙ БГ ЕООД № 107'),
  ('ТРАЙЧО РУУФ КЪМПАНИ ГРУП 2023 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/S7xSQLAC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТРАЙЧО РУУФ КЪМПАНИ ГРУП 2023 ЕООД № 160'),
  ('ТРАНСИНКО ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/uzg2TRKC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТРАНСИНКО ЕООД № 126'),
  ('ТС Кънстракшън ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/z7wmWaAT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТС Кънстракшън ЕООД № 165'),
  ('ТСАКИ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/bq5AHRxI', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТСАКИ ООД № 132'),
  ('ТТ ГРУП - 2010 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/LqQnGRhQ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ТТ ГРУП - 2010 ООД № 69'),
  ('УЗУНОВ ТРАНС 90 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/zjwhWIaA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / УЗУНОВ ТРАНС 90 ООД № 127'),
  ('УЛТРА ФЛЕКС ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/XmoWiRyb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / УЛТРА ФЛЕКС ООД № 37'),
  ('ФАЕЛ ГРУП ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OzIT2LgC', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ФАЕЛ ГРУП ЕООД № 176'),
  ('ФАРМАЛАЙЗ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/OyYA3L5a', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ФАРМАЛАЙЗ ООД'),
  ('ФЕЕРИЯ -98 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/XqRQWTJa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ФЕЕРИЯ -98 ЕООД - № 2'),
  ('ФЕЙЗАЛ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/WzBSgBaR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ФЕЙЗАЛ ЕООД № 143'),
  ('ФЕШЪН СЪПЛАЙ ЕАД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/jzI2VDpa', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ФЕШЪН СЪПЛАЙ ЕАД № 50'),
  ('ФОРЕСТ-70 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/mixB1YTB', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ФОРЕСТ-70 ЕООД № 209'),
  ('ФОТЕКС', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/uyIEQBya', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ФОТЕКС - № 12'),
  ('ХАСИ - ИНЖЕНЕРИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/z35E3ZIJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ХАСИ - ИНЖЕНЕРИНГ ЕООД № 99'),
  ('ХЕБЪРСТРОЙ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Kv42zQBZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ХЕБЪРСТРОЙ ООД № 177'),
  ('Хигиямед ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/n2AmmBbT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Хигиямед ООД № 66'),
  ('Хидройоникс', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/muZAWL5Q', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Хидройоникс № 5'),
  ('ХИМКОМЕРС - ИНЖЕНЕРИНГ ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/evgiyCKT', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ХИМКОМЕРС - ИНЖЕНЕРИНГ ООД'),
  ('ХИП 19 ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/Hy5SAD4I', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ХИП 19 ЕООД № 94'),
  ('ХоумМарт ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/2rYygTbY', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ХоумМарт ЕООД № 58'),
  ('ЧЕРНЕВ 2024 ООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/67xiDKiA', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЧЕРНЕВ 2024 ООД № 234'),
  ('ШАРАН ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/zrZE0bQR', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ШАРАН ЕООД № 215'),
  ('ШАРК СТРОЙ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/SqAFQDYZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ШАРК СТРОЙ ЕООД № 133'),
  ('ЯНЕВ ИНЖЕНЕРИНГ ЕООД', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/DyQETbxJ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / ЯНЕВ ИНЖЕНЕРИНГ ЕООД № 42'),
  ('briklabs', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/C2gE2AZD', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / briklabs'),
  ('DojoBits', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/DygRAKJb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / DojoBits'),
  ('EUR 2023 ОФЕРТА ДАККС БЪЛГАРСКИ ЕЗИК', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / EUR_2023_ОФЕРТА_ДАККС_БЪЛГАРСКИ ЕЗИК'),
  ('FB-03-009-BG Angaben für Angebote', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / FB-03-009-BG Angaben für Angebote'),
  ('Muehlbauer', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/u7hQiTBb', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / Muehlbauer'),
  ('WORLDGRID FRANCE SAS', 'https://mega.nz/folder/vvxAULDI#sc5y3rg4VtligSwYZ0D61Q/folder/nyQhlJbZ', 'active', 'Импорт от Mega папка. Път: СЕРТИФИКАЦИЯ / WORLDGRID FRANCE SAS')
) as v(name, mega_url, status, notes)
where not exists (
  select 1
  from companies c
  where lower(regexp_replace(c.name, '[^[:alnum:]]+', '', 'g')) =
        lower(regexp_replace(v.name, '[^[:alnum:]]+', '', 'g'))
);
